---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: flask-api-m:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password      
            - name: db_name
              value: flask1_mongo


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: flaskapi
  type: LoadBalancer
